'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace iSQL
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/ISQLServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="iSQL.webSQL")>  _
    Public Interface webSQL
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetData", ReplyAction:="http://tempuri.org/webSQL/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetData", ReplyAction:="http://tempuri.org/webSQL/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/webSQL/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As iSQL.CompositeType) As iSQL.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/webSQL/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As iSQL.CompositeType) As System.Threading.Tasks.Task(Of iSQL.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/Fill", ReplyAction:="http://tempuri.org/webSQL/FillResponse")>  _
        Function Fill(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal tableName As String, ByVal session_key As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/Fill", ReplyAction:="http://tempuri.org/webSQL/FillResponse")>  _
        Function FillAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal tableName As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/Update", ReplyAction:="http://tempuri.org/webSQL/UpdateResponse")>  _
        Function Update(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal dt() As Byte, ByVal session_key As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/Update", ReplyAction:="http://tempuri.org/webSQL/UpdateResponse")>  _
        Function UpdateAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal dt() As Byte, ByVal session_key As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ExecuteNonQuery", ReplyAction:="http://tempuri.org/webSQL/ExecuteNonQueryResponse")>  _
        Function ExecuteNonQuery(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ExecuteNonQuery", ReplyAction:="http://tempuri.org/webSQL/ExecuteNonQueryResponse")>  _
        Function ExecuteNonQueryAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ExecuteScalar", ReplyAction:="http://tempuri.org/webSQL/ExecuteScalarResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(iSQL.CompositeType))>  _
        Function ExecuteScalar(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ExecuteScalar", ReplyAction:="http://tempuri.org/webSQL/ExecuteScalarResponse")>  _
        Function ExecuteScalarAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetGroups", ReplyAction:="http://tempuri.org/webSQL/GetGroupsResponse")>  _
        Function GetGroups(ByVal username As String, ByVal password As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetGroups", ReplyAction:="http://tempuri.org/webSQL/GetGroupsResponse")>  _
        Function GetGroupsAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetUsers", ReplyAction:="http://tempuri.org/webSQL/GetUsersResponse")>  _
        Function GetUsers(ByVal username As String, ByVal password As String, ByVal filter As String, ByVal tableName As String, ByVal session_key As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/GetUsers", ReplyAction:="http://tempuri.org/webSQL/GetUsersResponse")>  _
        Function GetUsersAsync(ByVal username As String, ByVal password As String, ByVal filter As String, ByVal tableName As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ChangePassword", ReplyAction:="http://tempuri.org/webSQL/ChangePasswordResponse")>  _
        Function ChangePassword(ByVal username As String, ByVal password As String, ByVal password_new As String, ByVal session_key As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ChangePassword", ReplyAction:="http://tempuri.org/webSQL/ChangePasswordResponse")>  _
        Function ChangePasswordAsync(ByVal username As String, ByVal password As String, ByVal password_new As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ResetPassword", ReplyAction:="http://tempuri.org/webSQL/ResetPasswordResponse")>  _
        Function ResetPassword(ByVal username As String, ByVal password As String, ByVal username_new As String, ByVal password_new As String, ByVal session_key As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/ResetPassword", ReplyAction:="http://tempuri.org/webSQL/ResetPasswordResponse")>  _
        Function ResetPasswordAsync(ByVal username As String, ByVal password As String, ByVal username_new As String, ByVal password_new As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/getGS1info", ReplyAction:="http://tempuri.org/webSQL/getGS1infoResponse")>  _
        Function getGS1info(ByVal EAN_CODE As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/webSQL/getGS1info", ReplyAction:="http://tempuri.org/webSQL/getGS1infoResponse")>  _
        Function getGS1infoAsync(ByVal EAN_CODE As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface webSQLChannel
        Inherits iSQL.webSQL, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class webSQLClient
        Inherits System.ServiceModel.ClientBase(Of iSQL.webSQL)
        Implements iSQL.webSQL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements iSQL.webSQL.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements iSQL.webSQL.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As iSQL.CompositeType) As iSQL.CompositeType Implements iSQL.webSQL.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As iSQL.CompositeType) As System.Threading.Tasks.Task(Of iSQL.CompositeType) Implements iSQL.webSQL.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function Fill(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal tableName As String, ByVal session_key As String) As Byte() Implements iSQL.webSQL.Fill
            Return MyBase.Channel.Fill(query, parameters, tableName, session_key)
        End Function
        
        Public Function FillAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal tableName As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Byte()) Implements iSQL.webSQL.FillAsync
            Return MyBase.Channel.FillAsync(query, parameters, tableName, session_key)
        End Function
        
        Public Function Update(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal dt() As Byte, ByVal session_key As String) As Integer Implements iSQL.webSQL.Update
            Return MyBase.Channel.Update(query, parameters, dt, session_key)
        End Function
        
        Public Function UpdateAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal dt() As Byte, ByVal session_key As String) As System.Threading.Tasks.Task(Of Integer) Implements iSQL.webSQL.UpdateAsync
            Return MyBase.Channel.UpdateAsync(query, parameters, dt, session_key)
        End Function
        
        Public Function ExecuteNonQuery(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As Integer Implements iSQL.webSQL.ExecuteNonQuery
            Return MyBase.Channel.ExecuteNonQuery(query, parameters, session_key)
        End Function
        
        Public Function ExecuteNonQueryAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As System.Threading.Tasks.Task(Of Integer) Implements iSQL.webSQL.ExecuteNonQueryAsync
            Return MyBase.Channel.ExecuteNonQueryAsync(query, parameters, session_key)
        End Function
        
        Public Function ExecuteScalar(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As Object Implements iSQL.webSQL.ExecuteScalar
            Return MyBase.Channel.ExecuteScalar(query, parameters, session_key)
        End Function
        
        Public Function ExecuteScalarAsync(ByVal query As String, ByVal parameters As System.Collections.Generic.Dictionary(Of String, Object), ByVal session_key As String) As System.Threading.Tasks.Task(Of Object) Implements iSQL.webSQL.ExecuteScalarAsync
            Return MyBase.Channel.ExecuteScalarAsync(query, parameters, session_key)
        End Function
        
        Public Function GetGroups(ByVal username As String, ByVal password As String) As String Implements iSQL.webSQL.GetGroups
            Return MyBase.Channel.GetGroups(username, password)
        End Function
        
        Public Function GetGroupsAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of String) Implements iSQL.webSQL.GetGroupsAsync
            Return MyBase.Channel.GetGroupsAsync(username, password)
        End Function
        
        Public Function GetUsers(ByVal username As String, ByVal password As String, ByVal filter As String, ByVal tableName As String, ByVal session_key As String) As Byte() Implements iSQL.webSQL.GetUsers
            Return MyBase.Channel.GetUsers(username, password, filter, tableName, session_key)
        End Function
        
        Public Function GetUsersAsync(ByVal username As String, ByVal password As String, ByVal filter As String, ByVal tableName As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Byte()) Implements iSQL.webSQL.GetUsersAsync
            Return MyBase.Channel.GetUsersAsync(username, password, filter, tableName, session_key)
        End Function
        
        Public Function ChangePassword(ByVal username As String, ByVal password As String, ByVal password_new As String, ByVal session_key As String) As Boolean Implements iSQL.webSQL.ChangePassword
            Return MyBase.Channel.ChangePassword(username, password, password_new, session_key)
        End Function
        
        Public Function ChangePasswordAsync(ByVal username As String, ByVal password As String, ByVal password_new As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Boolean) Implements iSQL.webSQL.ChangePasswordAsync
            Return MyBase.Channel.ChangePasswordAsync(username, password, password_new, session_key)
        End Function
        
        Public Function ResetPassword(ByVal username As String, ByVal password As String, ByVal username_new As String, ByVal password_new As String, ByVal session_key As String) As Boolean Implements iSQL.webSQL.ResetPassword
            Return MyBase.Channel.ResetPassword(username, password, username_new, password_new, session_key)
        End Function
        
        Public Function ResetPasswordAsync(ByVal username As String, ByVal password As String, ByVal username_new As String, ByVal password_new As String, ByVal session_key As String) As System.Threading.Tasks.Task(Of Boolean) Implements iSQL.webSQL.ResetPasswordAsync
            Return MyBase.Channel.ResetPasswordAsync(username, password, username_new, password_new, session_key)
        End Function
        
        Public Function getGS1info(ByVal EAN_CODE As String) As String Implements iSQL.webSQL.getGS1info
            Return MyBase.Channel.getGS1info(EAN_CODE)
        End Function
        
        Public Function getGS1infoAsync(ByVal EAN_CODE As String) As System.Threading.Tasks.Task(Of String) Implements iSQL.webSQL.getGS1infoAsync
            Return MyBase.Channel.getGS1infoAsync(EAN_CODE)
        End Function
    End Class
End Namespace
