Public Class FN_MASTER_RECEIPT
    Public OU_CODE As String
    Public DIV_CODE As String
    Public SUB_TYPE As String
    Public RECEIPT_CODE As String
    Public RECEIPT_DATE As Date
    Public REF_SUB_TYPE As String
    Public REF_NO As String
    Public REF_DATE As Date
    Public PL_DIV_CODE As String
    Public PROJ_ID As String
    Public ATV_CODE As String
    Public CASHIER_CODE As String
    Public ACCOUNT_NUMBER As String
    Public CURR_CODE As String
    Public ARTYPE_CODE As String
    Public AR_CODE As String
    Public BANK_CODE As String
    Public BRANCH_CODE As String
    Public EX_RATE As Double
    Public REMARK As String
    Public CR_BY As String
    Public CR_DATE As Date
    Public UPD_BY As String
    Public UPD_DATE As Date
    Public PROG_ID As String
    Public SYSTEM_ID As String
    Public RECEIPT_AMT As String
    Public PRINT_NUM As Integer
    Public DELIVER_YN As String
    Public CANCEL_FLAG As String
    Public CANCEL_REASON As String
    Public CANCEL_BY As String
    Public CANCEL_DATE As Date
    Public CLOSE_YN As String
    Public REF_ITF_GL As String
    Public TAX_YN As String
    Public USE_FLAG As String
    Public AR_NAME As String
    Public CR_PROG_ID As String
    Public VAT_RATE As Double
    Public VAT_TYPE As String
    Public GROSS_AMT As Double
    Public PAY_AMT As Double
    Public PAY_DATE As Double
    Public RN_AMT As Double
    Public BAL_AMT As Double
    Public NOTE As String
    Public POST_GL_DATE As Date
    Public REF_GL As String
    Public TAX_ID As String
End Class
