Public Class IV_HEAD

    Public OU_CODE As String
    Public DIV_CODE As String
    Public SUB_TYPE As String
    Public TRAN_NO As String
    Public TRAN_DATE As Date
    Public BUDGET_YEAR As Integer
    Public BUDGET_PERIOD As Integer
    Public PROJ_ID As String
    Public ATV_CODE As String
    Public ARTYPE_CODE As String
    Public CURR_CODE As String
    Public EX_RATE As Double
    Public TOT_GROSS_AMT As Double
    Public TOT_DISC_RATE1 As Double
    Public TOT_DISC_RATE2 As Double
    Public TOT_DISC_BAHT As Double
    Public TOT_DISC_AMT As Double
    Public TOT_NET_AMT As Double
    Public VAT_RATE As Double
    Public TOT_VAT_AMT As Double
    Public TOTAL_AMT As Double
    Public BAL_AMT As Double
    Public DN_AMT As Double
    Public CN_AMT As Double
    Public PAY_AMT As Double
    Public NOTE As String
    Public SYSTEM_ID As String
    Public REF_ITF_GL As String
    Public CANCEL_FLAG As String
    Public CANCEL_REASON As String
    Public CANCEL_DATE As Date
    Public CANCEL_BY As String
    Public PRINT_NUM As Integer
    Public CLOSE_YN As String
    Public TAX_YN As String
    Public CR_BY As String
    Public CR_DATE As Date
    Public UPD_BY As String
    Public UPD_DATE As Date
    Public PROG_ID As String
    Public MB_MEMBER_CODE As String
    Public AR_CODE As String
    Public AR_DIV_CODE As String
    Public CR_TERM As Integer
    Public DUE_DATE As Date
    Public VAT_TYPE As String
    Public REGIST_CODE As String
    Public REPRINT_NOTE As String
    Public AR_ADDRESS_TEXT As String
End Class
