Public Class PN_HEAD

    Public OU_CODE As String
    Public DIV_CODE As String
    Public TRAN_NO As String
    Public PN_TRAN_NO As String
    Public IV_TRAN_NO As String
    Public RC_TRAN_NO As String
    Public TRAN_DATE As Date
    Public TRAN_TYPE As String
    Public BUDGET_YEAR As Integer
    Public BUDGET_PERIOD As Integer
    Public PROJ_ID As String
    Public ATV_CODE As String
    Public ARTYPE_CODE As String
    Public CURR_CODE As String
    Public VAT_RATE As Double
    Public EX_RATE As Double
    Public U_PRICE As Double
    Public U_PRICE_VAT As Double
    Public U_PRICE_INC_VAT As Double
    Public NET_U_PRICE As Double
    Public NET_U_PRICE_VAT As Double
    Public NET_U_PRICE_INC_VAT As Double
    Public DISC_AMT As Double
    Public DISC_AMT_VAT As Double
    Public DISC_AMT_INC_VAT As Double
    Public TOTAL As Double
    Public TOTAL_VAT As Double
    Public SUM_TOTAL As Double
    Public TOP_DISC_AMT As Double
    Public GRAND_AMT As Double
    Public GRAND_AMT_VAT As Double
    Public GRAND_AMT_INC_VAT As Double
    Public BAL_AMT As Double
    Public DN_AMT As Double
    Public CN_AMT As Double
    Public PAY_AMT As Double
    Public NOTE As String
    Public CANCEL_FLAG As String
    Public CANCEL_REASON As String
    Public CANCEL_DATE As Date
    Public CANCEL_BY As String
    Public PRINT_NUM As Integer
    Public CLOSE_YN As String
    Public TAX_YN As String
    Public CR_BY As String
    Public CR_DATE As Date
    Public UPD_BY As String
    Public UPD_DATE As Date
    Public PROG_ID As String
    Public MB_MEMBER_CODE As String
    Public AR_CODE As String
    Public AR_DIV_CODE As String
    Public CR_TERM As Integer
    Public DUE_DATE As Date
    Public VAT_TYPE As String
    Public REPRINT_NOTE As String
    Public RECEIPT_DOC_NO As String
    Public RN_AMT As Double
    Public TAX_ID As String
    Public POST_INVOICE_FLAG As String
    Public POST_RECEIPT_FLAG As String
    Public INNER_NOTE As String
    Public CANCEL_REJECT_REASON As String


End Class
